plugins {
    id 'java'
}

group = 'cn.sky'
version = '1.0-SNAPSHOT'

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-Xlint:unchecked')
    targetCompatibility = '25'
    sourceCompatibility = '25'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

repositories {
    maven {
        name = 'aliyun-repo'
        url = 'https://maven.aliyun.com/repository/public'
    }
}

dependencies {
    implementation 'org.ow2.asm:asm:9.9'
    implementation 'org.ow2.asm:asm-commons:9.9'
    implementation 'org.ow2.asm:asm-tree:9.9'
    implementation 'org.ow2.asm:asm-analysis:9.9'
    implementation 'org.ow2.asm:asm-util:9.9'
    implementation 'org.apache.logging.log4j:log4j-api:2.17.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.1'
    implementation "org.bspfsystems:yamlconfiguration:3.0.2"

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
}

jar {
    archiveFileName = 'jnic.jar'
    manifest {
        attributes(
                'Main-Class': 'cn.sky.jnic.Main'
        )
    }
}